Repository CSI-280/MusicGames, pull requests merged in 2020-04, with the labels that each got.

#51 fixed black page on refresh from game bug
  frontend/gui/src/App.js
  frontend/gui/src/Pages/games/GameHub.js
  frontend/gui/src/Pages/games/gameNav.js
  frontend/gui/src/components/navbar.js
Labels: Assignment 4

#68 Fix tic tac toe bug
  frontend/gui/src/components/tic_tac_toe.js
Labels: Assignment 5

#77 issue #69 - clean up styles once more before presentation
  frontend/gui/src/Pages/games/Connect4.js
  frontend/gui/src/Pages/games/GameHub.js
  frontend/gui/src/Pages/games/GuessArtist.js
  frontend/gui/src/Pages/games/gameNav.css
  frontend/gui/src/Pages/games/gameNav.js
  frontend/gui/src/components/Points.css
  frontend/gui/src/components/tic_tac_toe.css
  frontend/gui/src/components/tic_tac_toe.js
  frontend/gui/src/index.css
Labels: Assignment 6
